name: CI #워크플로우의 이름

on: #워크플로우가 트리거 될 조건을 정의 (아래는 "main" 브랜치로의 푸시 이벤트가 트리거 조건)
  push:
    branches: [ "main" ] #push할 경우 사용 할 branch 명 기입
  pull_request:
    branches: [ "main" ]  # master branch로 pull request될 때 실행됩니다.

jobs: #여러 작업(job)을 정의할 수 있는 곳
  deploy: # 작업의 이름
    runs-on: ubuntu-latest # 작업을 실행할 환경을 정의(여기서는 최신 Ubuntu 사용)

    #Checkout : Repository 의 코드들을 가져옵니다.
    steps:
      - name: Checkout
        uses: actions/checkout@v3 #저장소의 코드를 체크아웃하는 액션 사용

      #Setting JDK
      - name: Set up JDK 17 
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' # temurin 배포판의 JDK 17 사용

      #Setting yml
      - name: make application.yml
        run: | 
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}"  > src/main/resources/application.yml
          find src
      #gradlew chmod
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # ./gradlew 파일에 실행 권한 부여

      - name: Build with Gradle
        run: ./gradlew build
